// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// LightsGet implements GET /lights operation.
//
// Returns current lights for software implementations.
//
// GET /lights
func (UnimplementedHandler) LightsGet(ctx context.Context) (r *LightColor, _ error) {
	return r, ht.ErrNotImplemented
}

// ReportPost implements POST /report operation.
//
// Reports the current status for monitored tuple.
//
// POST /report
func (UnimplementedHandler) ReportPost(ctx context.Context, req *ClientReport) (r *Result, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetGet implements GET /reset operation.
//
// Resets the system.
//
// GET /reset
func (UnimplementedHandler) ResetGet(ctx context.Context) (r *Result, _ error) {
	return r, ht.ErrNotImplemented
}

// StatusGet implements GET /status operation.
//
// Returns current status.
//
// GET /status
func (UnimplementedHandler) StatusGet(ctx context.Context) (r *Status, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
